CODE_BASE_DIR = /home/jovyan/pipelines
WORK_BASE_DIR = /home/jovyan/work/tmp



create_code_dir:
	mkdir -p $WORK_BASE_DIR

copy_samples_clustering_code:
	cp $(CODE_BASE_DIR)/Samples_Clustering_Pipeline/src/  ..............
